# Generated by Django 4.2.17 on 2025-01-01 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_padd_db'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_TB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=450)),
                ('Price', models.CharField(max_length=250)),
                ('ServiceCentreName', models.CharField(max_length=450)),
                ('Quantity', models.CharField(max_length=50)),
                ('AddAddress', models.CharField(max_length=1000)),
                ('Services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service_db')),
                ('sp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.padd_db')),
                ('uf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.com_tb')),
            ],
        ),
    ]
