# Generated by Django 5.0.7 on 2025-01-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages_Tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Messages', models.CharField(max_length=900)),
                ('Date', models.DateField(max_length=10)),
                ('Time', models.TimeField(max_length=50)),
                ('Send_id', models.CharField(max_length=50)),
                ('Receiver_id', models.CharField(max_length=50)),
                ('Send_name', models.CharField(max_length=50)),
                ('Receiver_name', models.CharField(max_length=50)),
            ],
        ),
    ]
