# Generated by Django 5.1 on 2025-02-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_messages_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_tb',
            name='Bookingstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book_tb',
            name='Paymentstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='com_tb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='user/%Y/%m/%d/'),
        ),
    ]
