# Generated by Django 5.1.5 on 2025-03-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_book_tb_bookingstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com_tb',
            name='Address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='com_tb',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='com_tb',
            name='FullName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='com_tb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='com_tb',
            name='Location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='com_tb',
            name='Password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='com_tb',
            name='PinAddress',
            field=models.CharField(max_length=10),
        ),
    ]
