# Generated by Django 5.1 on 2025-03-09 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_communitypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages_tb',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
