# Generated by Django 5.1 on 2025-03-09 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_padd_db_services'),
        ('user', '0011_messages_tb_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages_tb',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='messages_tb',
            name='Messages',
        ),
        migrations.RemoveField(
            model_name='messages_tb',
            name='Receiver_id',
        ),
        migrations.RemoveField(
            model_name='messages_tb',
            name='Receiver_name',
        ),
        migrations.RemoveField(
            model_name='messages_tb',
            name='Send_id',
        ),
        migrations.RemoveField(
            model_name='messages_tb',
            name='Send_name',
        ),
        migrations.RemoveField(
            model_name='messages_tb',
            name='Time',
        ),
        migrations.AddField(
            model_name='messages_tb',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages_tb',
            name='message',
            field=models.TextField(default='No message'),
        ),
        migrations.AddField(
            model_name='messages_tb',
            name='receiver_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_service', to='service.service_db'),
        ),
        migrations.AddField(
            model_name='messages_tb',
            name='receiver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='user.com_tb'),
        ),
        migrations.AddField(
            model_name='messages_tb',
            name='sender_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_service', to='service.service_db'),
        ),
        migrations.AddField(
            model_name='messages_tb',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='user.com_tb'),
        ),
        migrations.AlterField(
            model_name='messages_tb',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
