# Generated by Django 5.1 on 2025-03-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_messages_tb_date_remove_messages_tb_messages_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages_Tb',
        ),
    ]
