# Generated by Django 4.2.17 on 2024-12-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='com_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CentreName', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=450)),
                ('Location', models.CharField(max_length=350)),
                ('Address', models.CharField(max_length=350)),
                ('PinAddress', models.CharField(max_length=350)),
                ('CentreImage', models.ImageField(upload_to='service')),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
