# Generated by Django 4.2.17 on 2024-12-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='com_DB',
            new_name='Service_DB',
        ),
    ]
