# Generated by Django 5.0.7 on 2025-01-18 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_service_db_centreimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padd_db',
            name='Review',
        ),
    ]
