# Generated by Django 5.0.7 on 2025-01-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_padd_db_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_db',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
