# Generated by Django 5.1.5 on 2025-03-06 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_db_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padd_db',
            name='Services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service_db'),
        ),
    ]
